<div>
    <p>
    <p><b>Isaac Asimov</b>, (born January 2, 1920, Petrovichi, Russia—died April 6, 1992, New York, New York, U.S.), American author and biochemist, a highly successful and prolific writer of science fiction and of science books for the layperson. He wrote or edited about 500 volumes, of which the most famous are those in the Foundation and robot series.</p>
    <p>Asimov was brought to the United States at age three. He grew up in Brooklyn, New York, and graduated from Columbia University in 1939. During World War II, he worked at the Naval Aviation Experimental Station in Philadelphia along with science-fiction authors Robert Heinlein and L. Sprague de Camp. After the war, he took a Ph.D. in chemistry from Columbia in 1948. He then joined the faculty of Boston University, with which he remained associated thereafter.</p>
    <p>Asimov began contributing stories to science-fiction magazines in 1939. He sold his first story, “Marooned off Vesta” to Amazing Stories, but he was most closely associated with Astounding Science-Fiction and its editor, John W. Campbell, Jr., who became a mentor to Asimov. <b>“Nightfall”</b> (1941), about a planet in a multiple-star system that only experiences darkness for one night every 2,049 years, brought him to the front rank of science-fiction writers and is regarded as one of the genre’s greatest short stories.</p>
    <p>In 1940 Asimov began writing his robot stories (later collected in I, Robot [1950]). In the 21st century, “positronic” robots operate according to the <b>Three Laws of Robotics</b>:
        <ol>
            <b><i><li>A robot may not injure a human being, or, through inaction, allow a human being to come to harm;</li></i></b>
            <b><i><li>a robot must obey the orders given it by human beings except where such orders would conflict with the First Law; and</li></i></b>
            <b><i><li>a robot must protect its own existence as long as such protection does not conflict with the First or Second Laws.</li></i></b>
        </ol>
    </p>
    <p>By developing (with Campbell) a set of ethics for robots and rejecting previous conceptions of them as marauding metal monsters, Asimov greatly influenced other writers’ treatment of the subject.</p>
    <p><b>“The Encyclopedists”</b> (1942) was the beginning of Asimov’s popular Foundation series. Loosely modeled on the fall of the Roman Empire, the Foundation series begins in the last days of the Galactic Empire. Hari Seldon devises a discipline, “psychohistory,” that allows prediction of future historical currents. He sets into motion a plan to reduce the predicted 30,000-year galactic dark ages to 1,000 years by gathering the brightest minds on the planet Terminus to form the Foundation of a new Galactic Empire. Seldon also establishes a mysterious Second Foundation in an unknown location. The Foundation struggles to keep civilization alive, while, at moments of acute crisis predicted by psychohistory, recordings of the long-dead Seldon dispense advice. The stories, written between 1942 and 1949, were collected as the Foundation trilogy: Foundation (1951), Foundation and Empire (1952), and Second Foundation (1953). The trilogy won a special Hugo Award in 1966 for best science-fiction series of all time.</p>
    <p>Asimov’s first novels (<b>Pebble in the Sky</b> [1950], <b>The Stars, Like Dust</b> [1951], and <b>The Currents of Space</b> [1952]) were set during and before the Galactic Empire but had no relation to the Foundation series. Under the pseudonym Paul French, he wrote the children’s Lucky Starr series (1952–58), each volume of which took place on a different world of the solar system. He returned to the positronic robots with two novels that blended mystery with science fiction. Three thousand years hence, humanity is divided between those who live on Earth in overpopulated underground cities and the wealthy Spacers, who live on worlds around nearby stars. The human policeman Lije Baley and the Spacer “humaniform” robot detective R. Daneel Olivaw solve murders in New York City in <b>The Caves of Steel</b> (1954) and on a Spacer planet in <b>The Naked Sun</b> (1957). During the 1950s, Asimov also wrote some of his finest short stories: <b>“The Martian Way”</b> (1952), an allegory about McCarthyism; <b>“The Dead Past”</b> (1956), about a device that can see into history; and <b>“The Ugly Little Boy”</b> (1958, original title “Lastborn”), about a nurse’s attachment to a Neanderthal child accidentally brought forward to the future.</p>
    <p>In the late 1950s, Asimov turned from science fiction to concentrate more on nonfiction writing. From 1958 to 1991, he wrote a monthly column about science for The Magazine of Fantasy and Science Fiction, which received a special Hugo Award in 1963. Much of his nonfiction writing was on various topics in science, written with lucidity and humour, ranging from chemistry (The Chemicals of Life [(1954]) to physics (The Neutrino [1975]) to biology (<b>The Human Brain</b> [(1964]). He even wrote on literature (<b>Asimov’s Guide to Shakespeare</b>, 2 vol. [1970]) and religion (<b>Asimov’s Guide to the Bible</b>, 2 vol. [1968–69]).</p>
    <p>Asimov returned to science fiction with <b>The Gods Themselves</b> (1972, winner of the Hugo and Nebula Awards) concerned contact with advanced aliens from a parallel universe. <b>“The Bicentennial Man”</b> (1976, Hugo and Nebula for best novelette), about a robot’s quest to become human is one of Asimov’s most beloved short stories.</p>
    <p>In the 1980s Asimov tied together the robot, Empire, and Foundation series in the same fictional universe. The characters in <b>Foundation’s Edge</b> (1982, Hugo Award for best novel) begin to suspect that a third, concealed power has emerged in the galaxy that is even more powerful than the two Foundations. Baley and Olivaw reunited in <b>The Robots of Dawn</b> (1983), in which they investigate the destruction of a robot identical to Olivaw. In <b>Robots and Empire</b> (1985), set 200 years after Baley’s death, Olivaw battles a threat to humanity that culminates in the diaspora from Earth that leads to the galactic Empire. <b>Foundation and Earth</b> (1986) centers on a search for the forgotten planet Earth and how its early history as depicted in the robot series affected the galaxy’s history. Two prequels to the Foundation trilogy, <b>Prelude to Foundation</b> (1988) and <b>Forward the Foundation</b> (1993), Asimov’s final novel, follow Hari Seldon’s development of psychohistory and the Foundation plan.</p>
    <p>Among Asimov’s late novels were expansions of previous short stories, written with Robert Silverberg, such as <b>Nightfall</b> (1990) and <b>Child of Time</b> (1991, based on “The Ugly Little Boy”). He published three volumes of autobiography: <b>In Memory Yet Green: The Autobiography of Isaac Asimov, 1920–1954</b> (1979); <b>In Joy Still Felt: .The Autobiography of Isaac Asimov, 1954–1978</b> (1980); and <b>I, Asimov: A Memoir </b>(1994, Hugo Award for best nonfiction book).</p><br><br>
    <div class="text-right">
         <i> Written By: Erik Gregersen</i>
        <p><b><i>Source: </i></b><a href="https://www.britannica.com/biography/Isaac-Asimov">Isaac Asimov | Biography &amp; Facts | Britannica</a></p>
    </div>
   </p>
</div>


